# Generated by Django 4.2.20 on 2025-05-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
