# Generated by Django 4.2.20 on 2025-06-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_gameboard_paths_config_alter_imageclick_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
