# Generated by Django 4.2.20 on 2025-05-07 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_userimage_uploaded_at_alter_userimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='main.userimage')),
            ],
        ),
    ]
