# Generated by Django 4.2.20 on 2025-05-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_imageclick_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for the common image.', max_length=100, unique=True)),
                ('image', models.ImageField(help_text='The actual image file.', upload_to='common_images/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, help_text='Optional description.', null=True)),
            ],
            options={
                'verbose_name': 'Common Image',
                'ordering': ['name'],
            },
        ),
    ]
