# Generated by Django 4.2.20 on 2025-05-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_commonimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='commonimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Original image height', null=True),
        ),
        migrations.AddField(
            model_name='userimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Original image width', null=True),
        ),
        migrations.AlterField(
            model_name='commonimage',
            name='image',
            field=models.ImageField(height_field='height', help_text='The actual image file.', upload_to='common_images/%Y/%m/%d/', width_field='width'),
        ),
        migrations.AlterField(
            model_name='imageclick',
            name='x',
            field=models.FloatField(help_text='X coordinate relative to original image dimensions'),
        ),
        migrations.AlterField(
            model_name='imageclick',
            name='y',
            field=models.FloatField(help_text='Y coordinate relative to original image dimensions'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(height_field='height', upload_to='uploads/%Y/%m/%d/', width_field='width'),
        ),
    ]
