# Generated by Django 4.2.20 on 2025-05-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_commonimage_height_commonimage_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonimage',
            name='height',
        ),
        migrations.RemoveField(
            model_name='commonimage',
            name='width',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='height',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='width',
        ),
        migrations.AlterField(
            model_name='commonimage',
            name='image',
            field=models.ImageField(help_text='The actual image file.', upload_to='common_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='imageclick',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='imageclick',
            name='y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
